### PR TITLE
Enable testing & formatting to ensure a clean codebase

### LINKED ISSUE #7: Add Pylint + Unit Tests

### PR DESCRIPTION
**Pull request by ghost**
This PR enables unittesting, formatting and uses pipenv as it's bases.
I've enabled caching, currently this wont work, as pipenv lockfiles do not really support cross-platform dependencies.
In the future we should enable this somehow.

I've also investigated Poetry, as I have no experience with it, I still went for pipenv, as it works really well.
Maybe someone has experience with Poetry and can provide some insights.

### CODE REVIEW

**Comment by Bonifatius94** [comment]
Your pipeline looks fine so far. I'm not really into pipenv (just using pylint / pytest), so I can't really tell if it's any good, but seems legit. Even though, I wouldn't use too fancy Python tooling as this is still a very small project which doesn't need such tools.

Code formatting looks fine as well, although it's not really pythonic, but we'll need to figure out what the linter says about it 😂 Which linter are you using btw?

**Comment by DooomiT** [comment]
I wouldn't say it's fancy tooling, just some basics here and there.
Black is used for formatting, which is somehow a non-opinionated formatter.
I always thought pythonic is more about the coding style and less about the formatting around it.
If you have some issues, black could be configured.

Pipenv ist just a layer around everything in order to substitute tasks to scripts and have a better dependency management.

Linting is currently not implemented.
I guess, not sure if you have any good linters in mind, I guess there are many out there.

**Comment by Bonifatius94** [comment]
> Black is used for formatting, which is somehow a non-opinionated formatter.

We don't need an auto-formatter. If the linter passes, it's good enough 😂 (and Python linters like pylint tend to be quite pedantic at enforcing a very specific coding style 😅)

> I'll add that :D & Pytest is used

Oh great! pytest is easy. If you're unsure how to set it up, you can have a look at my boilerplate on my GitHub

**Comment by DooomiT** [comment]
> > Black is used for formatting, which is somehow a non-opinionated formatter.
> 
> We don't need an auto-formatter. If the linter passes, it's good enough 😂 (and Python linters like pylint tend to be quite pedantic at enforcing a very specific coding style 😅)

Yeah, that's true, in the projects I contribute to, this helps to keep everything clean.
But I'm also fine with removing it again and just using a linter.

> > I'll add that :D & Pytest is used
> 
> Oh great! pytest is easy. If you're unsure how to set it up, you can have a look at my boilerplate on my GitHub

Allright, great.

**Comment by Bonifatius94** [comment]
> > > Black is used for formatting, which is somehow a non-opinionated formatter.
> > 
> > 
> > We don't need an auto-formatter. If the linter passes, it's good enough 😂 (and Python linters like pylint tend to be quite pedantic at enforcing a very specific coding style 😅)
> 
> Yeah, that's true, in the projects I contribute to, this helps to keep everything clean. But I'm also fine with removing it again and just using a linter.
> 
> > > I'll add that :D & Pytest is used
> > 
> > 
> > Oh great! pytest is easy. If you're unsure how to set it up, you can have a look at my boilerplate on my GitHub
> 
> Allright, great.

So I think you can go ahead and do the final changes we've just agreed on. But maybe consider reverting the auto-formatted code files. I did actually put quite some effort into making it look the way it was before your auto-formatter came along 😂

**Pull request merged**
